---
- name: Add qbtt repo
  command: add-apt-repository ppa:qbittorrent-team/qbittorrent-stable -y
  register: qbtt_repo_result
  changed_when: "'Found existing deb entry' not in qbtt_repo_result.stdout"
  become: true

- name: Install packages
  apt:
    pkg: "{{ apt_packages }}"
    state: present
    update_cache: true
  become: true